### ISSUE TITLE
How do you use a Privileged Access Token?

### ISSUE THREAD

**Issue by djones** [tradegecko/gecko#38]
The basic usage in the readme shows:

```ruby
client = Gecko::Client.new(CLIENT_ID, CLIENT_SECRET)
client.access_token = existing_access_token
```

But `existing_access_token` is going to be `nil` and no where does it actually explain what or where you get that from. So this basic usage example leads you down a failing path.

I'm creating an integration for TradeGecko that will be running standalone on a server so I need some sort of API token to work without any browser related auths going on. I've generated a Privileged Access Token for this application, which I think is the right thing to use, but I can't figure out actually how I use that token with this gem.

When I use `curl` I can indeed make API calls easily with just the Privileged Access Token. E.g.:

```
curl -H "Authorization: Bearer PRIVILEDGED_ACCESS_TOKEN" https://api.tradegecko.com/accounts
```

**Comment by djones** [comment]
This is the impression I got in terms of how I would use the privileged access token:

```ruby
client = Gecko::Client.new(CLIENT_ID, CLIENT_SECRET)
client.access_token = PRIVILEDGED_ACCESS_TOKEN
products = client.Product.where(q: "Whatever")
```

When running this I get:

```ruby
NoMethodError: undefined method `request' for #<String:0x007fa863a8a3c8>
```

Because it calls `request` on the `access_token` which is a String. But it's supposed to be something else? https://github.com/tradegecko/gecko/blob/master/lib/gecko/record/base_adapter.rb#L380

**Comment by bradleypriest** [comment]
Hey David,
Firstly, long time no see, I hope you're well.

Secondly, privileged access token were only recently added to the API, so we haven't put the proper helper methods into the gem yet.

What you want to do is:
```ruby
client = Gecko::Client.new(CLIENT_ID, CLIENT_SECRET)
client.authorize_from_existing(PRIVILEGED_TOKEN, nil, nil)
client.where(q: "Whatever")
```
