### ISSUE TITLE
Nicer API for retreiving all objects

### ISSUE THREAD

**Issue by djones** [tradegecko/gecko#41]
I want to get all products. Looking at the API docs you can do so by calling `https://api.tradegecko.com/products/`

A call to this API is not exposed directly right now in the Ruby client. Calling `where()` with no params is a workaround for now. E.g:

``` ruby
tradegecko = Gecko::Client.new(ENV['TRADEGECKO_CLIENT_ID'], ENV['TRADEGECKO_CLIENT_SECRET'])
tradegecko.authorize_from_existing(ENV['TRADEGECKO_CLIENT_TOKEN'], nil, nil)

tradegecko.Product.where() # => currently gets all products
```

It'd be nicer to have something like:

``` ruby
tradegecko.Product.all()
```

**Comment by jGRUBBS** [comment]
:+1:

**Comment by lcpriest** [comment]
It would just be an alias to where(), is that fine?

**Comment by djones** [comment]
yeah, @lcpriest at the end of the day it's just a bit of syntax sugar.

**Comment by lcpriest** [comment]
I would love a PR ;)

**Comment by lcpriest** [comment]
Ah. The reasoning was the following
```
It's not an all method, as it is paginated. We can add it, but it would be a direct alias to where, which still being paginated.
```

**Comment by lcpriest** [comment]
@djones given the pagination limitations, do you have any thoughts on this?
