### ISSUE TITLE
Can't create invoice without invoice line items

### ISSUE THREAD

**Issue by wassimk** [tradegecko/gecko#44]
When I try to create an invoice it asks me to include the invoice line items. I'm doing so but it strips them out. Please look at this and let me know if you see anything wrong:

``` ruby
tg_invoice = {
              :order_id => 4719140,
              :invoiced_at => Fri, 30 Jan 2015 00:00:00 EST -05:00,
              :invoice_line_items => [{
                :quantity => 3.0,
                :order_line_item_id => 9303792
             }]
}

invoice = $client.Invoice.build(tg_invoice)
```

After _invoice_ changes to:

``` ruby
{
                       :id => nil,
               :updated_at => nil,
               :created_at => nil,
                 :order_id => 4719140,
      :shipping_address_id => nil,
       :billing_address_id => nil,
          :payment_term_id => nil,
    :invoice_line_item_ids => [],
           :invoice_number => nil,
              :invoiced_at => Fri, 30 Jan 2015 00:00:00 EST -05:00,
                   :due_at => nil,
                    :notes => nil,
            :exchange_rate => nil,
          :destination_url => nil,
             :document_url => nil
}
```

_invoice.errors.messages_ gives me:

``` ruby
{:base=>["Cannot create invoice without line items"]}
```

**Comment by wassimk** [comment]
I also tried creating *InvoiceLineItem* objects and appending them to *invoice.invoice_line_items* before running save but the same situation. Your help is appreciated.

**Comment by bradleypriest** [comment]
Yeah, embedded items isn't supported yet sadly.
https://github.com/tradegecko/gecko/issues/4

Gonna leave this open, because it's something we want to be resolving pretty quicky

**Comment by denislutz** [comment]
Hey Guys,

any progress on that? We are stuck here as well.

Thanks.

**Comment by bradleypriest** [comment]
Sadly, no we haven't looked at this yet.
For the meantime, you can jump down to raw JSON pretty easily

```ruby 
invoice = gecko.Invoice.build(invoice_attrs)
items   = [gecko.InvoiceLineItem.build(item1_attrs), gecko.InvoiceLineItem.build(item2_attrs)]

response = gecko.access_token.post("/invoices", body: {
  invoice: invoice.as_json.merge(invoice_line_items: items.map(&:as_json))
})

created_invoice = gecko.Invoice.build(response.parsed_body)
```

Hope that helps

**Comment by wassimk** [comment]
@bradleypriest , this should work for updating too, right? I'm updating about 80 order line items with tax information and I'm having to do it one at a time with the GEM. Which is taking me over the API limits. A lot going on with this TradeGecko transition so I haven't sat down to test it. Can you validate mass updating order line items with one API call would work?

**Comment by lcpriest** [comment]
Yep, that should work.

**Comment by bradleypriest** [comment]
We don't currently have support for updating OrderLineItems embedded inside Orders

**Comment by wassimk** [comment]
Hey, sorry, just to validate before we abandon the feature and go to manual updating each line. Even if I drop down to JSON it won't work? The API itself doesn't support it?

**Comment by lcpriest** [comment]
@wassimk apparently not, I'll check into why and see if it's necessary.

**Comment by egerlach** [comment]
@bradleypriest This doesn't look like the code you provided works any longer. I'm trying to do the same thing with purchase orders. I've modified your code to:
```
# order and lines are the PurchaseOrder and Array[PurchaseOrderLineItems] respectively

# removed hash keys, as .as_json provides those now
request_body = order.as_json.merge(
  purchase_order_line_items: lines.map { |l| l.as_json[:purchase_order_line_item] }
)

response = gecko.access_token.post("/purchase_orders", body: request_body)

# .parsed_body becomes .parsed and have to index into it
created_purchase_order = client.PurchaseOrder.build(response.parsed["purchase_order"])
```

I'm getting the purchase order created, but it has no line items. At one point I was getting errors back from the API endpoint, but I'm not now, just nothing. Do you know what the JSON I should be sending to that endpoint to be able to use the embedded line items is? I'd prefer not to have to drop to a background job and loop using up my API calls.

@wassimk Are you still able to do a create with the embedded line items for invoices? Did you have to change your code at all from the above?

**Comment by nontone** [comment]
for me

```ruby
invoice_attrs = {
  order_id: order.id,
  billing_address_id: address.id,
  shipping_address_id: address.id,
  invoiced_at: Date.current.to_s
}
item1_attrs = { quantity: 1, order_line_item_id: line_item.id }
invoice_attrs = invoice_attrs.merge(invoice_line_items: [item1_attrs])

response = client.access_token.post("/invoices", body: {
  invoice: invoice_attrs
})
invoice = client.Invoice.build(response.parsed['invoice'])
```

**Comment by bradleypriest** [comment]
This is now supported in the following format (on master branch, soon to be 0.5)

```ruby
invoice = client.Invoice.build({
  order_id: order.id,
  billing_address_id: address.id,
  shipping_address_id: address.id,
  invoiced_at: Date.current
})

invoice.invoice_line_items.build({ 
  quantity: 1, 
  order_line_item_id: line_item.id 
})

invoice.save
```

**Comment by srennuse** [comment]
@bradleypriest 
TG probably should update their API documentation, wasted about an hour trying to create an invoice getting the error "Invoice must have lines" until I found this post.

As per your comment on 09/07/2018 the format that worked is: **invoice_line_items**

But in the TG API documentation it has: **invoice_line_item_ids** - which doesn't work and just throws back a 422 error.
