### ISSUE TITLE
Please add user to the order object

### ISSUE THREAD

**Issue by wassimk** [tradegecko/gecko#60]
I'm looking at user as the person who entered the order. 
I'm using assignee as the sales person who owns the customer relationship and thus the order.

I'm seeing it in the API but not the gem.

Thoughts?

**Comment by wassimk** [comment]
I went to add it but it's already there.. Here is what I was doing. I have a JSON field in my order table and I do an `as_json` on the TradeGecko order object and store it. I see that `as_json` is removing a lot of fields. I had no idea until now. A different issue to fix?

**Comment by wassimk** [comment]
Hey, one more thing, similar to this. Can we add the user who last created or updated an Address? Right now TradeGecko allows free form input for the state and country. I am validating they entered a correct address for shipping purposes. If the state or country they enter is not in my database I need to tell the user who did the create or update to fix it.

**Comment by bradleypriest** [comment]
Hi @wassimk `as_json` is used for serializing the object for saving, the `User` object and other fields you're seeing missing are all marked as `readonly` and therefore excluded from the JSON representation for save.

I'll let @lcpriest jump in to see if he has a good workaround for your usecase

**Comment by lcpriest** [comment]
With regards to the address changes, we don't currently store the last_updated_by on the object. It is not something I had considered a use for before, so will need to be architected on our end. We technically have the data, but it would require an extra preload on the API endpoint and the table that stores it is quite slow.
