### ISSUE TITLE
Add rate limit information

### ISSUE THREAD

**Issue by wassimk** [tradegecko/gecko#62]
Just a request to add easy methods to access current rate limit information. I have a list of 5000+ variants and I need to set the value of a custom attribute. I'm sleeping every **X** requests right now but the rate limit information would make it easier. I may be missing something obvious so guidance on a faster way for this one-off is appreciated.

**Comment by lcpriest** [comment]
I think there is a branch for that! https://github.com/tradegecko/gecko/commit/4ea8d714a4869f082b78b2a84c705b4264d4a0ff
Ping @bradleypriest

**Comment by lcpriest** [comment]
@wassimk do you think you could write a PR using this? https://github.com/tradegecko/gecko/pull/63

**Comment by bradleypriest** [comment]
Closed by #63
