### ISSUE TITLE
Procurements

### ISSUE THREAD

**Issue by mcrisologo** [tradegecko/gecko#68]
How are procurements created here? Or are they not supported yet?

**Comment by bradleypriest** [comment]
Hi @mcrisologo they are not documented in the API at this time as the API for Procurements is still subject to change.

That being said, the API is live if you're happy with the caveat that it may still change.

**Comment by mcrisologo** [comment]
Hi @bradleypriest thanks for the prompt response! Yes, we are still in Beta as well anyway. Still just poking stuff. 
If you could point me to the right direction, it would be much appreciated.

**Comment by bradleypriest** [comment]
Hi @mcrisologo, easiest way is to go into the web app, and inspect the request the app makes when you hit "Receive" on a Purchase Order, the API is exactly equivalent for the frontend as it is for the API.

**Comment by mcrisologo** [comment]
@bradleypriest Thanks for your time, Brad!

**Comment by itzRamkumar** [comment]
Hi @bradleypriest 

Procurement create for purchase order is still not completed?

**Comment by bradleypriest** [comment]
Hey @itzramkumar, same story, we still haven’t finalized this API, it’s something we’re looking to tackle this year though. 

In the short term, you’re welcome to inspect the web requests for insights, under the proviso that the api is still subject to change.

**Comment by byeggina** [comment]
Hi @bradleypriest

Do we have an update on the procurement API yet ?

Thanks,

**Comment by bradleypriest** [comment]
Hi @byeggina, nothing new to add at this time, the previous comment still holds.
Cheers
