### ISSUE TITLE
Is there are any way to create company with addresses in one request?

### ISSUE THREAD

**Issue by dpsk** [tradegecko/gecko#70]
How to create embedded resources? I don't see any documentation on that matter.

```
company = gecko.Company.build(
      company_type: 'consumer',
      name: "test",
      shipping_address: {
        address_1: "whatever just testing rightnow"
      },
      billing_address: {
        address_1: "whatever just testing rightnow"
      }
    )

```

Tried this one, but had no luck

**Comment by bradleypriest** [comment]
Hi @dpsk at this time that is not supported

**Comment by dpsk** [comment]
It's not supported by api or this gem?
Can i help somehow?

**Comment by bradleypriest** [comment]
Sorry for the lack of clarity.
It's not supported by the API at this time.
