### ISSUE TITLE
Uninitialized constant OAuth2::Version (NameError)

### ISSUE THREAD

**Issue by gregblass** [tradegecko/gecko#77]
Using Rails 5.2.0, Ruby 2.4.0, gecko-ruby-0.2.5:

`/lib/gecko/client.rb:127:in `default_headers': uninitialized constant OAuth2::Version (NameError)`

Simply by adding a the following in /config/initializers/trade_gecko.rb:

`
gecko = Gecko::Client.new(
  Rails.application.secrets.trade_gecko_application_id, 
  Rails.application.secrets.trade_gecko_secret
)
`
I'm not even doing anything else but that and I'm still getting that error when I try to start my rails server.

**Comment by gregblass** [comment]
oauth2 version installed (from this gem's dependency): 0.6.1

**Comment by gregblass** [comment]
Here's the commit that did it: https://github.com/oauth-xx/oauth2/commit/d4b71ebdbf39d353b94a81afcb928ba0c9d95d75#diff-1718bdc4ec73595d93564c4120632fae

You're not specifying a version of oauth2 in your gemspec. When I ran 'bundle install' with this gem, it added oauth2 (0.6.1). This is incompatible with this gem.

You should specify at least 0.8.0 due to this change (and who knows if there are any others that break the library).

Common now. Amateur hour over here?

**Comment by bradleypriest** [comment]
Have just cut a new version with a minimum oauth2 version to help make sure noone else runs into this issue. 

As a side note, the 1.0 of `oauth2` was released over 4 years ago, I'd take a careful look at what other gem in your gemfile was requiring such an old version of the gem.

**Comment by gregblass** [comment]
I wonder what the heck gem I had that had a version of oauth so low! Thanks for cutting a new version so quickly. That should fix any other cases of this from happening!
