### ISSUE TITLE
Update a product's quantity?

### ISSUE THREAD

**Issue by gregblass** [tradegecko/gecko#78]
I've created TradeGecko products through the API to represent products in our custom e-commerce software. I need to be able to make a call to the API to update the quantity of those products (when the admin marks the order as shipped).

How can I do that? I can't seem to find it in the documentation anywhere. TradeGecko's support is extremely slow and hasn't been able to help me.

**Comment by bradleypriest** [comment]
Hi Greg, 
There's no way to manually set a stock level value in TradeGecko.

The stock levels are based on the actions happening on the variant, in this case, fulfilling the order in TradeGecko will automatically handle reducing the stock for you.

If for some reason you're not looking to track those ecommerce orders as Sales Orders in TradeGecko, you can create a StockAdjustment object to manage just the stock levels.

Hope that helps

**Comment by gregblass** [comment]
How can I create a stock adjustment through the API?

**Comment by gregblass** [comment]
Oh OK, so I should be creating a sales order?

**Comment by bradleypriest** [comment]
Hi Greg, Bill's gonna send you a quick email to connect on what you're building and any best practices he can recommend

**Comment by gregblass** [comment]
OK so if I want to create an order, it looks like I'm required to add a shipping address ID, a billing address ID, and a company ID. These people ordering our stuff are not companies, they're people. And we don't care about their addresses?

**Comment by gregblass** [comment]
Is there a place in the API documentation where it explains how to create a stock adjustment? I can't seem to find it anywhere.
