### ISSUE TITLE
How to create a product with variants?

### ISSUE THREAD

**Issue by gregblass** [tradegecko/gecko#79]
From the documentation:

"Create a new product
Creates a new product object. This endpoint also accepts embedded variants."

No documentation on how that is done. How is that done?

**Comment by gregblass** [comment]
It looks like this actually isn't implemented / possible? has_many :variants would need embedded: true, like orders has for line items? Its just confusing because the documentation says its possible, but it looks like its not in Ruby?

**Comment by bradleypriest** [comment]
Hi Greg, this isn't built into the gem, but a workaround is on the wiki 
https://github.com/tradegecko/gecko/wiki/Creating-Products-with-Nested-Variants
